# Generated by Django 4.1.1 on 2022-09-22 20:48

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoria_habilitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.BooleanField(default=False, max_length=1, verbose_name='Habilitação tipo A')),
                ('b', models.BooleanField(default=False, max_length=1, verbose_name='Habilitação tipo B')),
                ('c', models.BooleanField(default=False, max_length=1, verbose_name='Habilitação tipo C')),
                ('d', models.BooleanField(default=False, max_length=1, verbose_name='Habilitação tipo D')),
                ('e', models.BooleanField(default=False, max_length=1, verbose_name='Habilitação tipo E')),
                ('f', models.BooleanField(default=False, max_length=1, verbose_name='Habilitação tipo F')),
            ],
            options={
                'verbose_name_plural': 'Registro de inscrições',
            },
        ),
        migrations.CreateModel(
            name='registerCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=255, verbose_name='Cargo de Interesse?')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('sexo', models.IntegerField(null=True, verbose_name='Sexo')),
                ('naturalidade', models.CharField(max_length=255, null=True, verbose_name='Naturalidade')),
                ('nacionalidade', models.CharField(max_length=255, null=True, verbose_name='Nacionalidade')),
                ('altura', models.FloatField(max_length=4, verbose_name='Altura')),
                ('peso', models.CharField(max_length=50, verbose_name='Peso')),
                ('data_aniversario', models.DateField(verbose_name='Data de Nascimento')),
                ('idade', models.IntegerField(max_length=3, verbose_name='Idade')),
                ('celular', phone_field.models.PhoneField(max_length=31, verbose_name='Celular')),
                ('nome_pai', models.CharField(max_length=255, null=True, verbose_name='Nome do pai')),
                ('nome_mae', models.CharField(max_length=255, verbose_name='Nome da mãe')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('bairro', models.CharField(max_length=255, verbose_name='Bairro')),
                ('cep', models.IntegerField(max_length=8, verbose_name='Cep')),
                ('necessidade_especial', models.BooleanField(default=False, verbose_name='Possui necessidades especiais?')),
                ('necessidade_especial_descricao', models.TextField(max_length=3000, null=True, verbose_name='Possui necessidades especiais?')),
                ('habilitacao', models.BooleanField(verbose_name='Habilitação')),
                ('reservista', models.BooleanField(default=True, verbose_name='Reservista?')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='Cpf?')),
                ('rg', models.CharField(max_length=30, unique=True, verbose_name='Rg?')),
                ('orgao_expedidor', models.CharField(max_length=20, verbose_name='Orgão expedidor')),
                ('uf', models.CharField(choices=[('AC', 'Acre'), ('RO', 'Rondônia'), ('AM', 'Amazonas'), ('RR', 'Roraima'), ('AC', 'Acre'), ('PA', 'Rondônia'), ('AP', 'Amapá'), ('TO', 'Tocantins'), ('MA', 'Maranhão'), ('PI', 'Piauí'), ('CE', 'Ceará'), ('RN', 'Rio Grande do Norte'), ('PB', 'Paraíba'), ('PE', 'Pernambuco'), ('AL', 'Alagoas'), ('SE', 'Sergipe'), ('BA', 'Bahia'), ('MG', 'Minas Gerais'), ('ES', 'Espírito Santo'), ('RJ', 'Rio de Janeiro'), ('SP', 'São Paulo'), ('PR', 'Paraná'), ('SC', 'Santa Catarina\t'), ('RS', 'Rio Grande do Sul (*)'), ('MS', 'Mato Grosso do Sul'), ('MT', 'Mato Grosso'), ('GO', 'Goiás'), ('DF', 'Distrito Federal')], max_length=4, verbose_name='UF')),
                ('escolaridade', models.CharField(max_length=255, verbose_name='Escolaridade')),
                ('status_escolaridade', models.CharField(max_length=255, verbose_name='Status')),
                ('data_conclusao_escolaridade', models.DateField(verbose_name='Ano de conclusao')),
                ('instituicao', models.CharField(max_length=255, verbose_name='Instituição')),
                ('estado_civil', models.CharField(max_length=255, verbose_name='Estado civil')),
                ('estado_civil_conjulgue', models.CharField(max_length=255, null=True, verbose_name='Estado civil')),
                ('filhos', models.BooleanField(verbose_name='Filhos?')),
                ('filhos_quantidade', models.IntegerField(max_length=2, null=True, verbose_name='Quantidade de filhos')),
                ('filhos_moram', models.BooleanField(null=True, verbose_name='Moram com você?')),
                ('filhos_maior_idade', models.IntegerField(null=True, verbose_name='Quantos acima de 18?')),
                ('instagram', models.CharField(max_length=255, verbose_name='Instagram')),
                ('facebook', models.CharField(max_length=255, verbose_name='Facebook')),
                ('linkedIn', models.CharField(max_length=255, null=True, verbose_name='LinkedIn')),
                ('rendas', models.IntegerField(max_length=3, verbose_name='Quantas rendas além da sua?')),
                ('conta_em_banco', models.BooleanField(verbose_name='Possui conta em banco?')),
                ('bancos', models.CharField(max_length=255, verbose_name='Quais bancos?')),
                ('imovel', models.BooleanField(verbose_name='Possui imóvel?')),
                ('residencia', models.CharField(max_length=255, verbose_name='Mora em residencia')),
                ('transporte', models.BooleanField(verbose_name='Possui transporte?')),
                ('transporte_descricao', models.CharField(max_length=255, null=True, verbose_name='Qual tipo de transporte?')),
                ('parentes', models.BooleanField(verbose_name='Parentes na empresa?')),
                ('cursos', models.BooleanField(verbose_name='Possui cursos?')),
                ('parentes_descricao', models.TextField(null=True, verbose_name='Informe os cursos')),
                ('primeiro_emprego', models.BooleanField(verbose_name='Primeiro emprego?')),
                ('curriculo', models.FileField(null=True, upload_to='curriculo/%Y%m%d', verbose_name='Curriculo')),
                ('foto', models.ImageField(upload_to='foto/%Y%m%d', verbose_name='Foto')),
                ('categoria_habilitacao', models.ManyToManyField(max_length=1, to='landpage.categoria_habilitacao', verbose_name='Tipo de habilitação')),
            ],
            options={
                'verbose_name_plural': 'Registro de inscrições',
            },
        ),
    ]
