# Generated by Django 4.1.1 on 2022-09-22 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registercandidate',
            name='cursos_descricao',
            field=models.TextField(null=True, verbose_name='Informe os cursos'),
        ),
        migrations.RemoveField(
            model_name='registercandidate',
            name='categoria_habilitacao',
        ),
        migrations.AlterField(
            model_name='registercandidate',
            name='parentes_descricao',
            field=models.CharField(max_length=255, null=True, verbose_name='Quem é o parente?'),
        ),
        migrations.AddField(
            model_name='registercandidate',
            name='categoria_habilitacao',
            field=models.CharField(max_length=255, null=True, verbose_name='Tipo de habilitação'),
        ),
    ]
