# Generated by Django 4.1.1 on 2022-09-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0002_registercandidate_cursos_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registercandidate',
            name='atividade_penultima_empresa',
            field=models.TextField(max_length=3000, null=True, verbose_name='Principais atividades na penúltima empresa '),
        ),
        migrations.AddField(
            model_name='registercandidate',
            name='atividade_ultima_empresa',
            field=models.TextField(max_length=3000, null=True, verbose_name='Principais atividades na empresa'),
        ),
        migrations.AddField(
            model_name='registercandidate',
            name='cargo_penultima_empresa',
            field=models.CharField(max_length=255, null=True, verbose_name='Cargo da Penúltima empresa'),
        ),
        migrations.AddField(
            model_name='registercandidate',
            name='cargo_ultima_empresa',
            field=models.CharField(max_length=255, null=True, verbose_name='Cargo da última empresa'),
        ),
        migrations.AddField(
            model_name='registercandidate',
            name='ctps_assinada_penultima_empresa',
            field=models.BooleanField(null=True, verbose_name='CTPS assinada Penúltima empresa'),
        ),
        migrations.AddField(
            model_name='registercandidate',
            name='ctps_assinada_ultima_empresa',
            field=models.BooleanField(null=True, verbose_name='CTPS assinada'),
        ),
        migrations.AddField(
            model_name='registercandidate',
            name='data_admisao_penultima_empresa',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Admissão Penúltima empresa'),
        ),
        migrations.AddField(
            model_name='registercandidate',
            name='data_admisao_ultima_empresa',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Admissão'),
        ),
        migrations.AddField(
            model_name='registercandidate',
            name='data_demissao_penultima_empresa',
            field=models.BooleanField(null=True, verbose_name='Data de demissão Penúltima empresa'),
        ),
        migrations.AddField(
            model_name='registercandidate',
            name='data_demissao_ultima_empresa',
            field=models.DateField(blank=True, null=True, verbose_name='Data de demissão'),
        ),
        migrations.AddField(
            model_name='registercandidate',
            name='emprego_atual_ultima_empresa',
            field=models.BooleanField(null=True, verbose_name='Emprego atual'),
        ),
        migrations.AddField(
            model_name='registercandidate',
            name='empresa_destaque',
            field=models.CharField(max_length=255, null=True, verbose_name='Empresa destaque?'),
        ),
        migrations.AddField(
            model_name='registercandidate',
            name='endereco_penultima_empresa',
            field=models.CharField(max_length=255, null=True, verbose_name='Endereço da Penúltima empresa'),
        ),
        migrations.AddField(
            model_name='registercandidate',
            name='endereco_ultima_empresa',
            field=models.CharField(max_length=255, null=True, verbose_name='Endereço da última empresa'),
        ),
        migrations.AddField(
            model_name='registercandidate',
            name='motivo_saida_penultima_empresa',
            field=models.BooleanField(null=True, verbose_name='Motivo da saida Penúltima empresa'),
        ),
        migrations.AddField(
            model_name='registercandidate',
            name='motivo_saida_ultima_empresa',
            field=models.TextField(null=True, verbose_name='Motivo da saida'),
        ),
        migrations.AddField(
            model_name='registercandidate',
            name='nome_penultima_empresa',
            field=models.CharField(max_length=255, null=True, verbose_name='Penúltima empresa'),
        ),
        migrations.AddField(
            model_name='registercandidate',
            name='nome_ultima_empresa',
            field=models.CharField(max_length=255, null=True, verbose_name='Ultima empresa'),
        ),
        migrations.AddField(
            model_name='registercandidate',
            name='outro_emprego',
            field=models.BooleanField(null=True, verbose_name='Outro emprego?'),
        ),
        migrations.AddField(
            model_name='registercandidate',
            name='responsavel_penultima_empresa',
            field=models.CharField(max_length=255, null=True, verbose_name='Responsável Penúltima empresa'),
        ),
        migrations.AddField(
            model_name='registercandidate',
            name='responsavel_ultima_empresa',
            field=models.CharField(max_length=255, null=True, verbose_name='Responsável'),
        ),
        migrations.AddField(
            model_name='registercandidate',
            name='telefone_penultima_empresa',
            field=models.CharField(max_length=255, null=True, verbose_name='Telefone da Penúltima empresa'),
        ),
        migrations.AddField(
            model_name='registercandidate',
            name='telefone_ultima_empresa',
            field=models.CharField(max_length=255, null=True, verbose_name='Telefone da última empresa'),
        ),
        migrations.AddField(
            model_name='registercandidate',
            name='ultimo_salario_penultima_empresa',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ultimo Salário Penúltima empresa'),
        ),
        migrations.AddField(
            model_name='registercandidate',
            name='ultimo_salario_ultima_empresa',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ultimo Salário'),
        ),
        migrations.AlterField(
            model_name='registercandidate',
            name='cep',
            field=models.IntegerField(verbose_name='Cep'),
        ),
        migrations.AlterField(
            model_name='registercandidate',
            name='filhos_maior_idade',
            field=models.IntegerField(default=0, null=True, verbose_name='Quantos acima de 18?'),
        ),
        migrations.AlterField(
            model_name='registercandidate',
            name='filhos_quantidade',
            field=models.IntegerField(default=0, null=True, verbose_name='Quantidade de filhos'),
        ),
        migrations.AlterField(
            model_name='registercandidate',
            name='idade',
            field=models.IntegerField(verbose_name='Idade'),
        ),
        migrations.AlterField(
            model_name='registercandidate',
            name='rendas',
            field=models.IntegerField(default=0, verbose_name='Quantas rendas além da sua?'),
        ),
        migrations.AlterField(
            model_name='registercandidate',
            name='sexo',
            field=models.CharField(max_length=255, null=True, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='registercandidate',
            name='uf',
            field=models.CharField(choices=[('AC', 'Acre'), ('RO', 'Rondônia'), ('AM', 'Amazonas'), ('RR', 'Roraima'), ('AP', 'Amapá'), ('TO', 'Tocantins'), ('MA', 'Maranhão'), ('PI', 'Piauí'), ('CE', 'Ceará'), ('RN', 'Rio Grande do Norte'), ('PB', 'Paraíba'), ('PE', 'Pernambuco'), ('AL', 'Alagoas'), ('SE', 'Sergipe'), ('BA', 'Bahia'), ('MG', 'Minas Gerais'), ('ES', 'Espírito Santo'), ('RJ', 'Rio de Janeiro'), ('SP', 'São Paulo'), ('PR', 'Paraná'), ('SC', 'Santa Catarina\t'), ('RS', 'Rio Grande do Sul (*)'), ('MS', 'Mato Grosso do Sul'), ('MT', 'Mato Grosso'), ('GO', 'Goiás'), ('DF', 'Distrito Federal')], max_length=4, verbose_name='UF'),
        ),
    ]
