# Generated by Django 4.1.1 on 2022-09-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0003_registercandidate_atividade_penultima_empresa_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='categoria_habilitacao',
        ),
        migrations.AlterField(
            model_name='registercandidate',
            name='bancos',
            field=models.CharField(max_length=255, null=True, verbose_name='Quais bancos?'),
        ),
        migrations.AlterField(
            model_name='registercandidate',
            name='cep',
            field=models.CharField(max_length=10, verbose_name='Cep'),
        ),
        migrations.AlterField(
            model_name='registercandidate',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, verbose_name='Cpf?'),
        ),
        migrations.AlterField(
            model_name='registercandidate',
            name='filhos_quantidade',
            field=models.IntegerField(null=True, verbose_name='Quantidade de filhos'),
        ),
        migrations.AlterField(
            model_name='registercandidate',
            name='necessidade_especial',
            field=models.BooleanField(verbose_name='Possui necessidades especiais?'),
        ),
        migrations.AlterField(
            model_name='registercandidate',
            name='necessidade_especial_descricao',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Possui necessidades especiais?'),
        ),
        migrations.AlterField(
            model_name='registercandidate',
            name='orgao_expedidor',
            field=models.CharField(max_length=50, verbose_name='Orgão expedidor'),
        ),
        migrations.AlterField(
            model_name='registercandidate',
            name='peso',
            field=models.CharField(max_length=10, verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='registercandidate',
            name='rendas',
            field=models.IntegerField(verbose_name='Quantas rendas além da sua?'),
        ),
    ]
