# Generated by Django 4.1.1 on 2022-09-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0004_delete_categoria_habilitacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registercandidate',
            name='altura',
            field=models.CharField(max_length=4, verbose_name='Altura'),
        ),
    ]
