# Generated by Django 4.1.1 on 2022-09-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0005_alter_registercandidate_altura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registercandidate',
            name='cpf',
            field=models.CharField(max_length=14, verbose_name='Cpf?'),
        ),
        migrations.AlterField(
            model_name='registercandidate',
            name='rg',
            field=models.CharField(max_length=30, verbose_name='Rg?'),
        ),
    ]
