# Generated by Django 4.1.1 on 2022-09-27 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0006_alter_registercandidate_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registercandidate',
            name='categoria_habilitacao',
            field=models.TextField(null=True, verbose_name='Tipo de habilitação'),
        ),
    ]
