# Generated by Django 4.1.1 on 2022-09-27 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0007_alter_registercandidate_categoria_habilitacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registercandidate',
            name='data_demissao_penultima_empresa',
            field=models.DateField(null=True, verbose_name='Data de demissão Penúltima empresa'),
        ),
        migrations.AlterField(
            model_name='registercandidate',
            name='motivo_saida_penultima_empresa',
            field=models.TextField(null=True, verbose_name='Motivo da saida Penúltima empresa'),
        ),
    ]
