# Generated by Django 4.1.1 on 2022-09-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0008_alter_registercandidate_data_demissao_penultima_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registercandidate',
            name='pis',
            field=models.CharField(max_length=50, null=True, verbose_name='Principais atividades na empresa'),
        ),
    ]
