# Generated by Django 4.1.1 on 2022-10-01 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0011_gerenciadevagas_alter_registercandidate_facebook_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gerenciadevagas',
            options={'verbose_name_plural': 'Vagas abertas'},
        ),
    ]
