# Generated by Django 4.1.1 on 2022-10-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0013_registeremails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gerenciadevagas',
            name='ATENDENTE_DE_ADEGA',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gerenciadevagas',
            name='ATENDIMENTO_AO_CLIENTE',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gerenciadevagas',
            name='AUXILIAR_DE_DEPOSITO',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gerenciadevagas',
            name='AUX_DE_COZINHA',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gerenciadevagas',
            name='AUX_DE_DEPOSITO',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gerenciadevagas',
            name='AUX_DE_DEPOSITO_TRANSFERENCIA',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gerenciadevagas',
            name='AUX_LIMPEZA',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gerenciadevagas',
            name='AVARIA',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gerenciadevagas',
            name='AÇOUGUEIRO',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gerenciadevagas',
            name='CARTAZISTA',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gerenciadevagas',
            name='CFTV',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gerenciadevagas',
            name='CFTV_NOTURNO',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gerenciadevagas',
            name='CONFERENTE',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gerenciadevagas',
            name='CONFERENTE_DE_MERCADORIA_ENTRADA',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gerenciadevagas',
            name='CONFERENTE_DE_MERCADORIA_SAIDA',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gerenciadevagas',
            name='CONFERENTE_DE_MERCDORIA',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gerenciadevagas',
            name='CONTROLADOR_DE_ESTOQUE',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gerenciadevagas',
            name='COZINHEIRA',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gerenciadevagas',
            name='CREDIARIO',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gerenciadevagas',
            name='ECARREGADO_DEPOSITO',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gerenciadevagas',
            name='EMBALADOR',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gerenciadevagas',
            name='EMPILHADEIRA_GRANDE',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gerenciadevagas',
            name='ENCARREGADA_DE_CREDIARIO',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gerenciadevagas',
            name='ENCARREGADA_DE_TELEVENDAS',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gerenciadevagas',
            name='ENCARREGADO_DA_PADARIA',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gerenciadevagas',
            name='ENCARREGADO_DA_ROTISSERIA',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gerenciadevagas',
            name='ENCARREGADO_DE_ACOUGUE',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gerenciadevagas',
            name='ENCARREGADO_DE_FRENTE_DE_CAIXA',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gerenciadevagas',
            name='ENCARREGADO_DE_FRIOS',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gerenciadevagas',
            name='ENCARREGADO_DE_HORTI_FRUTI',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gerenciadevagas',
            name='ENCARREGADO_DE_PREVENÇAO',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gerenciadevagas',
            name='ENCARREGADO_MERCEARIA',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gerenciadevagas',
            name='FISCAL_DE_CAIXA',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gerenciadevagas',
            name='FISCAL_DE_PREVENÇÃO',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gerenciadevagas',
            name='GERENTE_LOJA',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gerenciadevagas',
            name='MOTORISTA',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gerenciadevagas',
            name='OPERADOR_DE_CAIXA',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gerenciadevagas',
            name='OPERADOR_DE_EMPILHADEIRA',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gerenciadevagas',
            name='PADARIA',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gerenciadevagas',
            name='PEIXEIRO',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gerenciadevagas',
            name='PREVENÇAO',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gerenciadevagas',
            name='REPOSITOR_DE_FRIOS',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gerenciadevagas',
            name='REPOSITOR_DE_HORTI_FRUTI',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gerenciadevagas',
            name='REPOSITOR_DE_MERCEARIA',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gerenciadevagas',
            name='RM',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gerenciadevagas',
            name='ROTISSERIA',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gerenciadevagas',
            name='SEPRADOR_DE_MERCADORIA',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gerenciadevagas',
            name='SUB_GERENTE',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gerenciadevagas',
            name='SUPERVISORA_E_COMERCE',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gerenciadevagas',
            name='SUPERVISOR_DE_CD',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gerenciadevagas',
            name='SUSHIMAN',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gerenciadevagas',
            name='TELEVENDAS',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gerenciadevagas',
            name='TESOURARIA',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
