# Generated by Django 4.1.1 on 2022-10-05 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0015_remove_gerenciadevagas_atendente_de_adega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gerenciadevagas',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Vaga ativa?'),
        ),
    ]
