# Generated by Django 4.1.1 on 2022-10-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0016_gerenciadevagas_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registercandidate',
            name='ultimo_salario_penultima_empresa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ultimo Salário Penúltima empresa'),
        ),
        migrations.AlterField(
            model_name='registercandidate',
            name='ultimo_salario_ultima_empresa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ultimo Salário'),
        ),
    ]
