# Generated by Django 4.1.1 on 2022-11-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0017_alter_registercandidate_ultimo_salario_penultima_empresa_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registercandidate',
            options={'verbose_name': 'uma inscrição', 'verbose_name_plural': 'Registro de inscrições'},
        ),
        migrations.AlterField(
            model_name='registercandidate',
            name='altura',
            field=models.CharField(max_length=4, null=True, verbose_name='Altura'),
        ),
        migrations.AlterField(
            model_name='registercandidate',
            name='filhos_maior_idade',
            field=models.CharField(default=0, max_length=255, null=True, verbose_name='Quantos acima de 18?'),
        ),
        migrations.AlterField(
            model_name='registercandidate',
            name='filhos_quantidade',
            field=models.CharField(max_length=255, null=True, verbose_name='Quantidade de filhos'),
        ),
        migrations.AlterField(
            model_name='registercandidate',
            name='idade',
            field=models.CharField(max_length=10, verbose_name='Idade'),
        ),
        migrations.AlterField(
            model_name='registercandidate',
            name='peso',
            field=models.CharField(max_length=10, null=True, verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='registercandidate',
            name='pis',
            field=models.CharField(max_length=50, null=True, verbose_name='Pis'),
        ),
        migrations.AlterField(
            model_name='registercandidate',
            name='rendas',
            field=models.CharField(max_length=255, verbose_name='Quantas rendas além da sua?'),
        ),
    ]
