# Generated by Django 4.1.1 on 2022-11-10 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0018_alter_registercandidate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registercandidate',
            name='transporte',
            field=models.BooleanField(null=True, verbose_name='Possui transporte?'),
        ),
    ]
