# Generated by Django 4.1.1 on 2022-12-30 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0019_alter_registercandidate_transporte'),
    ]

    operations = [
        migrations.CreateModel(
            name='imagenspromocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeImage', models.CharField(default='', max_length=255, verbose_name='Nome da imagem')),
                ('imagemDaVaga', models.ImageField(null=True, upload_to='', verbose_name='Imagem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Imagem ativa?')),
            ],
            options={
                'verbose_name_plural': 'Imagens promoção',
            },
        ),
    ]
