# Generated by Django 4.1.1 on 2022-12-30 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0020_imagenspromocao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gerenciadevagas',
            name='imagemDaVaga',
            field=models.ImageField(upload_to='imagespromo/', verbose_name='Imagem da vaga'),
        ),
    ]
